spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://15.164.233.242:3306/dream
    username: user
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # ?? ?? ??

    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true


